### ISSUE TITLE
Telegram is static

### ISSUE THREAD

**Issue by resulraveendran** [paulpierre/RasaGPT#18]
we are running on our local machine, we leverage Ngrok to generate a publically accessible URL and reverse tunnel into our docker container

  What are the steps i need to follow https://t.me/Medigy_rasagpt_bot this is my bot

**Comment by resulraveendran** [comment]
Hi,

     What are the troubleshooting methods we need to use make these bot active

**Comment by resulraveendran** [comment]
From chat_action we got this error 

Traceback (most recent call last):
15/05/2023 12:56:04
  File "handle_request", line 26, in handle_request
15/05/2023 12:56:04
    from socket import socket
15/05/2023 12:56:04
  File "/opt/venv/lib/python3.10/site-packages/sanic/router.py", line 66, in get
15/05/2023 12:56:04
    return self._get(path, method, host)
15/05/2023 12:56:04
  File "/opt/venv/lib/python3.10/site-packages/sanic/router.py", line 44, in _get
15/05/2023 12:56:04
    raise NotFound("Requested URL {} not found".format(e.path))
15/05/2023 12:56:04
sanic.exceptions.NotFound: Requested URL  not found
15/05/2023 12:56:04
2023-05-15 07:26:04 ERROR    rasa_sdk.endpoint  - Exception occurred during execution of request <Request: GET /favicon.ico>
15/05/2023 12:56:04
Traceback (most recent call last):
15/05/2023 12:56:04
  File "/opt/venv/lib/python3.10/site-packages/sanic_routing/router.py", line 79, in resolve
15/05/2023 12:56:04
    route, param_basket = self.find_route(
15/05/2023 12:56:04
  File "", line 9, in find_route
15/05/2023 12:56:04
sanic_routing.exceptions.NotFound: Not Found

**Comment by xxm1668** [comment]
me too
