### ISSUE TITLE
Organization already exists

### ISSUE THREAD

**Issue by vishwajeetio** [paulpierre/RasaGPT#32]
Getting the error below when running the command
make install.

Traceback (most recent call last):
  File "/app/api/seed.py", line 128, in <module>
    org_obj = create_org_by_org_or_uuid(
  File "/app/api/helpers.py", line 95, in create_org_by_org_or_uuid
    raise HTTPException(status_code=404, detail="Organization already exists")
fastapi.exceptions.HTTPException
make[1]: *** [seed] Error 1
make: *** [install] Error 2

**Comment by BOTHRAJ** [comment]
Use the "**make db-reset**" command and then run the "**make install**" command again.
